include:
- template: Terraform/Base.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml

stages:
- init
- validate
- build
- deploy
- cleanup

init:
  extends: .init

validate:
  extends: .validate

build:
  extends: .build

deploy:
  extends: .deploy
  dependencies:
  - build
  when: manual

cleanup:
  extends: .destroy
  dependencies:
  - deploy
  when: manual
