name: Test Secret Action

on:
  push:
    branches:
      - test

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Show Test Secret Value
      run: |
        [ "${{ secrets.TEST }}" == "TEST_VALUE_FLAG" ] && echo "Test Pass" 
